[versions]
activityKtx = "1.11.0"
agp = "8.13.0"
blurview = "version-3.2.0"
firebaseCrashlyticsGradle = "3.0.6"
googleServices = "4.4.3"
fragmentKtx = "1.8.9"
ktorClientAndroid = "2.3.5"
multidex = "2.0.1"
switchbutton = "2.1.0"
lifecycleLivedataKtx = "2.9.4"
biometric = "1.1.0"
firebaseBom = "34.3.0"
supabaseBom = "2.0.0"
hiltAndroid = "2.57.1"
hiltAndroidGradlePlugin = "2.57.1"
kotlin = "2.2.20"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kotlinGradlePlugin = "2.0.21"
material = "1.13.0"
constraintlayout = "2.2.1"
navigationFragmentKtx = "2.9.4"
securityCrypto = "1.1.0"
mpandroidchart = "v3.1.0"
rollingtext = "1.3.0"
circleimageview = "3.1.0"
lottie = "6.6.9"
gson = "2.13.2"
shimmer = "0.5.0"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
blurview = { module = "com.github.Dimezis:BlurView", version.ref = "blurview" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
firebase-database = { module = "com.google.firebase:firebase-database" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroidGradlePlugin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClientAndroid" }
supabase-bom = { module = "io.github.jan-tennert.supabase:bom", version.ref = "supabaseBom" }
supabase-postgrest-kt = { module = "io.github.jan-tennert.supabase:postgrest-kt" }
switchbutton = { module = "com.kyleduo.switchbutton:library", version.ref = "switchbutton" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
rollingtext = { module = "com.github.YvesCheung.RollingText:RollingText", version.ref = "rollingtext" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
kotlin-kapt = { id = "kotlin-kapt" }
hilt = { id = "com.google.dagger.hilt.android" }
crashlytics = { id = "com.google.firebase.crashlytics" }